name: build_runner_benchmark_test
version: 0.0.1
description: A sample command-line application
homepage: https://github.com/DisDis/build_runner_benchmark
dependencies:

dev_dependencies:
  build_runner: ^0.8.0
  build_web_compilers: ^0.3.4+2
#  unittest: any
