name: build_runner_benchmark
version: 0.0.1
description: A sample command-line application
homepage: https://github.com/DisDis/build_runner_benchmark
dependencies:
  args: ^1.4.0
  path: ^1.5.1
  logging: ^0.11.0
  build_runner: ^0.8.0
  package_resolver: ^1.0.2
#dev_dependencies:
#  unittest: any
